image: archlinux
packages:
  - sbcl
sources:
  - https://git.sr.ht/~theo/lisp-ci
  - https://hg.sr.ht/~theo/gql
tasks:
  - setup: |
      ./lisp-ci/lisp-ci.sh
      mv ~/gql ~/quicklisp/local-projects/
      cd ~/quicklisp/local-projects/gql
  - test: |
      cd ~/quicklisp/local-projects/gql
      ./test.sh
      hg diff
