(in-package #:gql)

(defgeneric gql (input &optional debug)
  (:method :before (input &optional debug)
    (setf *debug-print* debug))
  (:method ((f pathname) &optional debug)
    (declare (ignorable debug))
    (let* ((str (slurp f))
           (*parser* (make-parser str)))
      (values str (parse 'document))))
  (:method ((str string) &optional debug)
    (declare (ignorable debug))
    (let ((*parser* (make-parser str)))
      (values str (parse 'document))))
  (:documentation "Entry point for lexing and parsing"))

(defgeneric build-schema (input)
  (:method ((f pathname))
    (let ((*parser* (make-parser (slurp f))))
      (parse 'document)))
  (:method ((str string))
    (let ((*parser* (make-parser str)))
      (parse 'document)))
  (:method ((types list))
    (make-instance 'document :definitions types))
  (:documentation "Build a GraphQL schema.
This is a simple helper to create a parsed document."))

(defgeneric build-document (input)
  (:method ((f pathname))
    (let ((*parser* (make-parser (slurp f))))
      (parse 'document)))
  (:method ((str string))
    (let ((*parser* (make-parser str)))
      (parse 'document)))
  (:method ((types list))
    (make-instance 'document :definitions types))
  (:documentation "Build a GraphQL schema.
This is a simple helper to create a parsed document."))
